//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polysol.Comercial.WebApp.AccesoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Credencial", Namespace="http://schemas.datacontract.org/2004/07/Filasur.AppCorp.Entities")]
    [System.SerializableAttribute()]
    public partial class Credencial : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CredencialIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaBloqueoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FlgBloqueoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FlgSesionAliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombrePersonalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PuestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PuestoDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Polysol.Comercial.WebApp.AccesoService.Sede SedeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SedeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioAliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioRedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Anexo {
            get {
                return this.AnexoField;
            }
            set {
                if ((object.ReferenceEquals(this.AnexoField, value) != true)) {
                    this.AnexoField = value;
                    this.RaisePropertyChanged("Anexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Celular {
            get {
                return this.CelularField;
            }
            set {
                if ((object.ReferenceEquals(this.CelularField, value) != true)) {
                    this.CelularField = value;
                    this.RaisePropertyChanged("Celular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CredencialId {
            get {
                return this.CredencialIdField;
            }
            set {
                if ((this.CredencialIdField.Equals(value) != true)) {
                    this.CredencialIdField = value;
                    this.RaisePropertyChanged("CredencialId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartamentoDesc {
            get {
                return this.DepartamentoDescField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoDescField, value) != true)) {
                    this.DepartamentoDescField = value;
                    this.RaisePropertyChanged("DepartamentoDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Empleado {
            get {
                return this.EmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadoField, value) != true)) {
                    this.EmpleadoField = value;
                    this.RaisePropertyChanged("Empleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaBloqueo {
            get {
                return this.FechaBloqueoField;
            }
            set {
                if ((this.FechaBloqueoField.Equals(value) != true)) {
                    this.FechaBloqueoField = value;
                    this.RaisePropertyChanged("FechaBloqueo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FlgBloqueo {
            get {
                return this.FlgBloqueoField;
            }
            set {
                if ((this.FlgBloqueoField.Equals(value) != true)) {
                    this.FlgBloqueoField = value;
                    this.RaisePropertyChanged("FlgBloqueo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FlgSesionAlias {
            get {
                return this.FlgSesionAliasField;
            }
            set {
                if ((this.FlgSesionAliasField.Equals(value) != true)) {
                    this.FlgSesionAliasField = value;
                    this.RaisePropertyChanged("FlgSesionAlias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombrePersonal {
            get {
                return this.NombrePersonalField;
            }
            set {
                if ((object.ReferenceEquals(this.NombrePersonalField, value) != true)) {
                    this.NombrePersonalField = value;
                    this.RaisePropertyChanged("NombrePersonal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Puesto {
            get {
                return this.PuestoField;
            }
            set {
                if ((object.ReferenceEquals(this.PuestoField, value) != true)) {
                    this.PuestoField = value;
                    this.RaisePropertyChanged("Puesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PuestoDesc {
            get {
                return this.PuestoDescField;
            }
            set {
                if ((object.ReferenceEquals(this.PuestoDescField, value) != true)) {
                    this.PuestoDescField = value;
                    this.RaisePropertyChanged("PuestoDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Polysol.Comercial.WebApp.AccesoService.Sede Sede {
            get {
                return this.SedeField;
            }
            set {
                if ((object.ReferenceEquals(this.SedeField, value) != true)) {
                    this.SedeField = value;
                    this.RaisePropertyChanged("Sede");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SedeId {
            get {
                return this.SedeIdField;
            }
            set {
                if ((this.SedeIdField.Equals(value) != true)) {
                    this.SedeIdField = value;
                    this.RaisePropertyChanged("SedeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioAlias {
            get {
                return this.UsuarioAliasField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioAliasField, value) != true)) {
                    this.UsuarioAliasField = value;
                    this.RaisePropertyChanged("UsuarioAlias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioRed {
            get {
                return this.UsuarioRedField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioRedField, value) != true)) {
                    this.UsuarioRedField = value;
                    this.RaisePropertyChanged("UsuarioRed");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sede", Namespace="http://schemas.datacontract.org/2004/07/Filasur.AppCorp.Entities")]
    [System.SerializableAttribute()]
    public partial class Sede : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Polysol.Comercial.WebApp.AccesoService.Empresa EmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmpresaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InicialSedeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NombreSedeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SedeIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((this.DireccionField.Equals(value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Polysol.Comercial.WebApp.AccesoService.Empresa Empresa {
            get {
                return this.EmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpresaField, value) != true)) {
                    this.EmpresaField = value;
                    this.RaisePropertyChanged("Empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmpresaId {
            get {
                return this.EmpresaIdField;
            }
            set {
                if ((this.EmpresaIdField.Equals(value) != true)) {
                    this.EmpresaIdField = value;
                    this.RaisePropertyChanged("EmpresaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InicialSede {
            get {
                return this.InicialSedeField;
            }
            set {
                if ((this.InicialSedeField.Equals(value) != true)) {
                    this.InicialSedeField = value;
                    this.RaisePropertyChanged("InicialSede");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NombreSede {
            get {
                return this.NombreSedeField;
            }
            set {
                if ((this.NombreSedeField.Equals(value) != true)) {
                    this.NombreSedeField = value;
                    this.RaisePropertyChanged("NombreSede");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SedeId {
            get {
                return this.SedeIdField;
            }
            set {
                if ((this.SedeIdField.Equals(value) != true)) {
                    this.SedeIdField = value;
                    this.RaisePropertyChanged("SedeId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empresa", Namespace="http://schemas.datacontract.org/2004/07/Filasur.AppCorp.Entities")]
    [System.SerializableAttribute()]
    public partial class Empresa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AbrevEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmpresaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsEntidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImgLogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreComercialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroRucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocialField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AbrevEmpresa {
            get {
                return this.AbrevEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.AbrevEmpresaField, value) != true)) {
                    this.AbrevEmpresaField = value;
                    this.RaisePropertyChanged("AbrevEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmpresaId {
            get {
                return this.EmpresaIdField;
            }
            set {
                if ((this.EmpresaIdField.Equals(value) != true)) {
                    this.EmpresaIdField = value;
                    this.RaisePropertyChanged("EmpresaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsEntidad {
            get {
                return this.EsEntidadField;
            }
            set {
                if ((this.EsEntidadField.Equals(value) != true)) {
                    this.EsEntidadField = value;
                    this.RaisePropertyChanged("EsEntidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImgLogo {
            get {
                return this.ImgLogoField;
            }
            set {
                if ((object.ReferenceEquals(this.ImgLogoField, value) != true)) {
                    this.ImgLogoField = value;
                    this.RaisePropertyChanged("ImgLogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreComercial {
            get {
                return this.NombreComercialField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreComercialField, value) != true)) {
                    this.NombreComercialField = value;
                    this.RaisePropertyChanged("NombreComercial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroRuc {
            get {
                return this.NroRucField;
            }
            set {
                if ((object.ReferenceEquals(this.NroRucField, value) != true)) {
                    this.NroRucField = value;
                    this.RaisePropertyChanged("NroRuc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial {
            get {
                return this.RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialField, value) != true)) {
                    this.RazonSocialField = value;
                    this.RaisePropertyChanged("RazonSocial");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Nodo", Namespace="http://schemas.datacontract.org/2004/07/Filasur.AppCorp.Entities")]
    [System.SerializableAttribute()]
    public partial class Nodo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsEstandarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FlgIntegradoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IconoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NodoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NodoPadreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrdenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Polysol.Comercial.WebApp.AccesoService.Software SoftwareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoftwareIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoNodoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UbicacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsEstandar {
            get {
                return this.EsEstandarField;
            }
            set {
                if ((this.EsEstandarField.Equals(value) != true)) {
                    this.EsEstandarField = value;
                    this.RaisePropertyChanged("EsEstandar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FlgIntegrado {
            get {
                return this.FlgIntegradoField;
            }
            set {
                if ((this.FlgIntegradoField.Equals(value) != true)) {
                    this.FlgIntegradoField = value;
                    this.RaisePropertyChanged("FlgIntegrado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Icono {
            get {
                return this.IconoField;
            }
            set {
                if ((object.ReferenceEquals(this.IconoField, value) != true)) {
                    this.IconoField = value;
                    this.RaisePropertyChanged("Icono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NodoId {
            get {
                return this.NodoIdField;
            }
            set {
                if ((this.NodoIdField.Equals(value) != true)) {
                    this.NodoIdField = value;
                    this.RaisePropertyChanged("NodoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NodoPadre {
            get {
                return this.NodoPadreField;
            }
            set {
                if ((this.NodoPadreField.Equals(value) != true)) {
                    this.NodoPadreField = value;
                    this.RaisePropertyChanged("NodoPadre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Orden {
            get {
                return this.OrdenField;
            }
            set {
                if ((this.OrdenField.Equals(value) != true)) {
                    this.OrdenField = value;
                    this.RaisePropertyChanged("Orden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Polysol.Comercial.WebApp.AccesoService.Software Software {
            get {
                return this.SoftwareField;
            }
            set {
                if ((object.ReferenceEquals(this.SoftwareField, value) != true)) {
                    this.SoftwareField = value;
                    this.RaisePropertyChanged("Software");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoftwareId {
            get {
                return this.SoftwareIdField;
            }
            set {
                if ((this.SoftwareIdField.Equals(value) != true)) {
                    this.SoftwareIdField = value;
                    this.RaisePropertyChanged("SoftwareId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoNodoId {
            get {
                return this.TipoNodoIdField;
            }
            set {
                if ((this.TipoNodoIdField.Equals(value) != true)) {
                    this.TipoNodoIdField = value;
                    this.RaisePropertyChanged("TipoNodoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ubicacion {
            get {
                return this.UbicacionField;
            }
            set {
                if ((object.ReferenceEquals(this.UbicacionField, value) != true)) {
                    this.UbicacionField = value;
                    this.RaisePropertyChanged("Ubicacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Software", Namespace="http://schemas.datacontract.org/2004/07/Filasur.AppCorp.Entities")]
    [System.SerializableAttribute()]
    public partial class Software : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Polysol.Comercial.WebApp.AccesoService.Empresa EmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmpresaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoftwareIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UbicacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Polysol.Comercial.WebApp.AccesoService.Empresa Empresa {
            get {
                return this.EmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpresaField, value) != true)) {
                    this.EmpresaField = value;
                    this.RaisePropertyChanged("Empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmpresaId {
            get {
                return this.EmpresaIdField;
            }
            set {
                if ((this.EmpresaIdField.Equals(value) != true)) {
                    this.EmpresaIdField = value;
                    this.RaisePropertyChanged("EmpresaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoftwareId {
            get {
                return this.SoftwareIdField;
            }
            set {
                if ((this.SoftwareIdField.Equals(value) != true)) {
                    this.SoftwareIdField = value;
                    this.RaisePropertyChanged("SoftwareId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ubicacion {
            get {
                return this.UbicacionField;
            }
            set {
                if ((object.ReferenceEquals(this.UbicacionField, value) != true)) {
                    this.UbicacionField = value;
                    this.RaisePropertyChanged("Ubicacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rol", Namespace="http://schemas.datacontract.org/2004/07/Filasur.AppCorp.Entities")]
    [System.SerializableAttribute()]
    public partial class Rol : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AbreviaturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RolIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Abreviatura {
            get {
                return this.AbreviaturaField;
            }
            set {
                if ((object.ReferenceEquals(this.AbreviaturaField, value) != true)) {
                    this.AbreviaturaField = value;
                    this.RaisePropertyChanged("Abreviatura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RolId {
            get {
                return this.RolIdField;
            }
            set {
                if ((this.RolIdField.Equals(value) != true)) {
                    this.RolIdField = value;
                    this.RaisePropertyChanged("RolId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccesoService.ISoftEmpAcceso")]
    public interface ISoftEmpAcceso {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoftEmpAcceso/ObtenerCredencial", ReplyAction="http://tempuri.org/ISoftEmpAcceso/ObtenerCredencialResponse")]
        Polysol.Comercial.WebApp.AccesoService.Credencial ObtenerCredencial(string p_Usuario, bool p_UsaERP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoftEmpAcceso/ObtenerCredencial", ReplyAction="http://tempuri.org/ISoftEmpAcceso/ObtenerCredencialResponse")]
        System.Threading.Tasks.Task<Polysol.Comercial.WebApp.AccesoService.Credencial> ObtenerCredencialAsync(string p_Usuario, bool p_UsaERP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoftEmpAcceso/ValidaAcceso", ReplyAction="http://tempuri.org/ISoftEmpAcceso/ValidaAccesoResponse")]
        Polysol.Comercial.WebApp.AccesoService.Credencial ValidaAcceso(string p_Usuario, string p_Clave, bool p_UsaERP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoftEmpAcceso/ValidaAcceso", ReplyAction="http://tempuri.org/ISoftEmpAcceso/ValidaAccesoResponse")]
        System.Threading.Tasks.Task<Polysol.Comercial.WebApp.AccesoService.Credencial> ValidaAccesoAsync(string p_Usuario, string p_Clave, bool p_UsaERP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoftEmpAcceso/ObtenerNodos", ReplyAction="http://tempuri.org/ISoftEmpAcceso/ObtenerNodosResponse")]
        Polysol.Comercial.WebApp.AccesoService.Nodo[] ObtenerNodos(string p_CodApp, string p_Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoftEmpAcceso/ObtenerNodos", ReplyAction="http://tempuri.org/ISoftEmpAcceso/ObtenerNodosResponse")]
        System.Threading.Tasks.Task<Polysol.Comercial.WebApp.AccesoService.Nodo[]> ObtenerNodosAsync(string p_CodApp, string p_Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoftEmpAcceso/ObtenerRol", ReplyAction="http://tempuri.org/ISoftEmpAcceso/ObtenerRolResponse")]
        Polysol.Comercial.WebApp.AccesoService.Rol ObtenerRol(string p_CodApp, string p_Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoftEmpAcceso/ObtenerRol", ReplyAction="http://tempuri.org/ISoftEmpAcceso/ObtenerRolResponse")]
        System.Threading.Tasks.Task<Polysol.Comercial.WebApp.AccesoService.Rol> ObtenerRolAsync(string p_CodApp, string p_Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoftEmpAcceso/CambiarPassword", ReplyAction="http://tempuri.org/ISoftEmpAcceso/CambiarPasswordResponse")]
        int CambiarPassword(string p_CredencialId, string p_ClaveAnterior, string p_ClaveNueva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoftEmpAcceso/CambiarPassword", ReplyAction="http://tempuri.org/ISoftEmpAcceso/CambiarPasswordResponse")]
        System.Threading.Tasks.Task<int> CambiarPasswordAsync(string p_CredencialId, string p_ClaveAnterior, string p_ClaveNueva);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISoftEmpAccesoChannel : Polysol.Comercial.WebApp.AccesoService.ISoftEmpAcceso, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SoftEmpAccesoClient : System.ServiceModel.ClientBase<Polysol.Comercial.WebApp.AccesoService.ISoftEmpAcceso>, Polysol.Comercial.WebApp.AccesoService.ISoftEmpAcceso {
        
        public SoftEmpAccesoClient() {
        }
        
        public SoftEmpAccesoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SoftEmpAccesoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoftEmpAccesoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoftEmpAccesoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Polysol.Comercial.WebApp.AccesoService.Credencial ObtenerCredencial(string p_Usuario, bool p_UsaERP) {
            return base.Channel.ObtenerCredencial(p_Usuario, p_UsaERP);
        }
        
        public System.Threading.Tasks.Task<Polysol.Comercial.WebApp.AccesoService.Credencial> ObtenerCredencialAsync(string p_Usuario, bool p_UsaERP) {
            return base.Channel.ObtenerCredencialAsync(p_Usuario, p_UsaERP);
        }
        
        public Polysol.Comercial.WebApp.AccesoService.Credencial ValidaAcceso(string p_Usuario, string p_Clave, bool p_UsaERP) {
            return base.Channel.ValidaAcceso(p_Usuario, p_Clave, p_UsaERP);
        }
        
        public System.Threading.Tasks.Task<Polysol.Comercial.WebApp.AccesoService.Credencial> ValidaAccesoAsync(string p_Usuario, string p_Clave, bool p_UsaERP) {
            return base.Channel.ValidaAccesoAsync(p_Usuario, p_Clave, p_UsaERP);
        }
        
        public Polysol.Comercial.WebApp.AccesoService.Nodo[] ObtenerNodos(string p_CodApp, string p_Usuario) {
            return base.Channel.ObtenerNodos(p_CodApp, p_Usuario);
        }
        
        public System.Threading.Tasks.Task<Polysol.Comercial.WebApp.AccesoService.Nodo[]> ObtenerNodosAsync(string p_CodApp, string p_Usuario) {
            return base.Channel.ObtenerNodosAsync(p_CodApp, p_Usuario);
        }
        
        public Polysol.Comercial.WebApp.AccesoService.Rol ObtenerRol(string p_CodApp, string p_Usuario) {
            return base.Channel.ObtenerRol(p_CodApp, p_Usuario);
        }
        
        public System.Threading.Tasks.Task<Polysol.Comercial.WebApp.AccesoService.Rol> ObtenerRolAsync(string p_CodApp, string p_Usuario) {
            return base.Channel.ObtenerRolAsync(p_CodApp, p_Usuario);
        }
        
        public int CambiarPassword(string p_CredencialId, string p_ClaveAnterior, string p_ClaveNueva) {
            return base.Channel.CambiarPassword(p_CredencialId, p_ClaveAnterior, p_ClaveNueva);
        }
        
        public System.Threading.Tasks.Task<int> CambiarPasswordAsync(string p_CredencialId, string p_ClaveAnterior, string p_ClaveNueva) {
            return base.Channel.CambiarPasswordAsync(p_CredencialId, p_ClaveAnterior, p_ClaveNueva);
        }
    }
}
